/* tslint:disable */
/* eslint-disable */
/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BaseResponse
 */
export interface BaseResponse {

    /**
     * @type {number}
     * @memberof BaseResponse
     */
    code: number;

    /**
     * @type {string}
     * @memberof BaseResponse
     */
    message: string;
}
