/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiauthdevicebindconfirmDeviceInfo } from './apiauthdevicebindconfirm-device-info';
/**
*
*
* @export
* @interface BindConfirmBody
*/
export interface BindConfirmBody {
    /**
     * 登录返回的 bindToken（短期有效）
     *
     * @type {string}
     * @memberof BindConfirmBody
     */
    bindToken: string;
    /**
     * @type {ApiauthdevicebindconfirmDeviceInfo}
     * @memberof BindConfirmBody
     */
    deviceInfo?: ApiauthdevicebindconfirmDeviceInfo;
}
