/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface IdOfflineBody
*/
export interface IdOfflineBody {
    /**
     * @type {string}
     * @memberof IdOfflineBody
     */
    reason?: string;
}
