/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface IdWatchBody
*/
export interface IdWatchBody {
    /**
     * @type {number}
     * @memberof IdWatchBody
     */
    lastPositionSec?: number | null;
    /**
     * 本次增量观看秒数（delta）
     *
     * @type {number}
     * @memberof IdWatchBody
     */
    watchedSeconds?: number | null;
    /**
     * @type {boolean}
     * @memberof IdWatchBody
     */
    completed?: boolean | null;
}
