/* tslint:disable */
/* eslint-disable */
/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseResponse } from './base-response';
import { InlineResponse20016Data } from './inline-response20016-data';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20016
 */
export interface InlineResponse20016 extends BaseResponse {

    /**
     * @type {InlineResponse20016Data}
     * @memberof InlineResponse20016
     */
    data: InlineResponse20016Data;
}
