/* tslint:disable */
/* eslint-disable */
/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseResponse } from './base-response';
import { VideoComment } from './video-comment';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2013
 */
export interface InlineResponse2013 extends BaseResponse {

    /**
     * @type {VideoComment}
     * @memberof InlineResponse2013
     */
    data: VideoComment;
}
