/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface InlineResponse200Data
*/
export interface InlineResponse200Data {
    /**
     * @type {string}
     * @memberof InlineResponse200Data
     */
    token: string;
    /**
     * @type {any}
     * @memberof InlineResponse200Data
     */
    user?: any | null;
}
