/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface InlineResponse20010DataRisk
*/
export interface InlineResponse20010DataRisk {
    /**
     * @type {boolean}
     * @memberof InlineResponse20010DataRisk
     */
    triggered: boolean;
    /**
     * @type {string}
     * @memberof InlineResponse20010DataRisk
     */
    riskType?: string;
    /**
     * @type {string}
     * @memberof InlineResponse20010DataRisk
     */
    severity?: InlineResponse20010DataRiskSeverityEnum;
    /**
     * @type {number}
     * @memberof InlineResponse20010DataRisk
     */
    alertId?: number;
}
/**
 * @export
 * @enum {string}
 */
export declare enum InlineResponse20010DataRiskSeverityEnum {
    LOW = "LOW",
    MEDIUM = "MEDIUM",
    HIGH = "HIGH"
}
