/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseResponse } from './base-response';
import { VideoWatchLog } from './video-watch-log';
/**
*
*
* @export
* @interface InlineResponse2004
*/
export interface InlineResponse2004 extends BaseResponse {
    /**
     * @type {VideoWatchLog}
     * @memberof InlineResponse2004
     */
    data: VideoWatchLog;
}
