/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface InlineResponse20011DataLastMessage
*/
export interface InlineResponse20011DataLastMessage {
    /**
     * @type {string}
     * @memberof InlineResponse20011DataLastMessage
     */
    role: InlineResponse20011DataLastMessageRoleEnum;
    /**
     * @type {string}
     * @memberof InlineResponse20011DataLastMessage
     */
    content: string;
}
/**
 * @export
 * @enum {string}
 */
export declare enum InlineResponse20011DataLastMessageRoleEnum {
    SYSTEM = "SYSTEM",
    USER = "USER",
    ASSISTANT = "ASSISTANT"
}
