/* tslint:disable */
/* eslint-disable */
/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * @export
 * @enum {string}
 */
export var LiveRoomStatusEnum;
(function (LiveRoomStatusEnum) {
    LiveRoomStatusEnum["DRAFT"] = "DRAFT";
    LiveRoomStatusEnum["REVIEW"] = "REVIEW";
    LiveRoomStatusEnum["PASSED"] = "PASSED";
    LiveRoomStatusEnum["PUBLISHED"] = "PUBLISHED";
    LiveRoomStatusEnum["REJECTED"] = "REJECTED";
    LiveRoomStatusEnum["LIVING"] = "LIVING";
    LiveRoomStatusEnum["FINISHED"] = "FINISHED";
    LiveRoomStatusEnum["OFFLINE"] = "OFFLINE";
})(LiveRoomStatusEnum || (LiveRoomStatusEnum = {}));
