/* tslint:disable */
/* eslint-disable */
/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OssUploadurlBody
 */
export interface OssUploadurlBody {

    /**
     * @type {string}
     * @memberof OssUploadurlBody
     */
    key?: string;

    /**
     * @type {string}
     * @memberof OssUploadurlBody
     */
    prefix?: string;

    /**
     * @type {string}
     * @memberof OssUploadurlBody
     */
    filename?: string;

    /**
     * @type {string}
     * @memberof OssUploadurlBody
     */
    contentType?: string;

    /**
     * @type {number}
     * @memberof OssUploadurlBody
     */
    expiresInSeconds?: number;
}
