/* tslint:disable */
/* eslint-disable */
/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, BaseAPI, RequiredError } from '../base';
/**
 * LiveApi - axios parameter creator
 * @export
 */
export const LiveApiAxiosParamCreator = function (configuration) {
    return {
        /**
         *
         * @summary 管理端直播列表（学院/平台管理员）
         * @param {string} [status] 默认 REVIEW
         * @param {number} [collegeId]
         * @param {number} [anchorId]
         * @param {string} [search]
         * @param {number} [page]
         * @param {number} [pageSize]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveAdminGet: async (status, collegeId, anchorId, search, page, pageSize, options = {}) => {
            const localVarPath = `/api/live/admin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }
            if (collegeId !== undefined) {
                localVarQueryParameter['collegeId'] = collegeId;
            }
            if (anchorId !== undefined) {
                localVarQueryParameter['anchorId'] = anchorId;
            }
            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }
            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }
            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 直播列表（公开）
         * @param {string} [tab]
         * @param {number} [collegeId]
         * @param {string} [search]
         * @param {number} [page]
         * @param {number} [pageSize]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveGet: async (tab, collegeId, search, page, pageSize, options = {}) => {
            const localVarPath = `/api/live`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            if (tab !== undefined) {
                localVarQueryParameter['tab'] = tab;
            }
            if (collegeId !== undefined) {
                localVarQueryParameter['collegeId'] = collegeId;
            }
            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }
            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }
            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 获取 Agora RTC Token（登录用户）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveIdAgoraRtcTokenPost: async (id, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiLiveIdAgoraRtcTokenPost.');
            }
            const localVarPath = `/api/live/{id}/agora/rtc-token`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 审核直播（学院管理员）
         * @param {string} id
         * @param {IdAuditBody1} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveIdAuditPost: async (id, body, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiLiveIdAuditPost.');
            }
            const localVarPath = `/api/live/{id}/audit`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            localVarHeaderParameter['Content-Type'] = 'application/json';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 结束直播（志愿者）
         * @param {string} id
         * @param {IdFinishBody} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveIdFinishPost: async (id, body, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiLiveIdFinishPost.');
            }
            const localVarPath = `/api/live/{id}/finish`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            localVarHeaderParameter['Content-Type'] = 'application/json';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 直播详情（公开）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveIdGet: async (id, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiLiveIdGet.');
            }
            const localVarPath = `/api/live/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 直播消息列表（登录用户）
         * @param {string} id
         * @param {number} [afterId]
         * @param {number} [limit]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveIdMessagesGet: async (id, afterId, limit, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiLiveIdMessagesGet.');
            }
            const localVarPath = `/api/live/{id}/messages`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            if (afterId !== undefined) {
                localVarQueryParameter['afterId'] = afterId;
            }
            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 发送直播消息（登录用户）
         * @param {string} id
         * @param {IdMessagesBody} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveIdMessagesPost: async (id, body, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiLiveIdMessagesPost.');
            }
            const localVarPath = `/api/live/{id}/messages`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            localVarHeaderParameter['Content-Type'] = 'application/json';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 下架直播（志愿者/管理员）
         * @param {string} id
         * @param {IdOfflineBody1} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveIdOfflinePost: async (id, body, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiLiveIdOfflinePost.');
            }
            const localVarPath = `/api/live/{id}/offline`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            localVarHeaderParameter['Content-Type'] = 'application/json';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 上架直播（志愿者）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveIdPublishPost: async (id, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiLiveIdPublishPost.');
            }
            const localVarPath = `/api/live/{id}/publish`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 开始直播（志愿者）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveIdStartPost: async (id, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiLiveIdStartPost.');
            }
            const localVarPath = `/api/live/{id}/start`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 获取直播推/拉流信息（登录用户）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveIdStreamGet: async (id, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiLiveIdStreamGet.');
            }
            const localVarPath = `/api/live/{id}/stream`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 提交直播审核（志愿者）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveIdSubmitPost: async (id, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id', 'Required parameter id was null or undefined when calling apiLiveIdSubmitPost.');
            }
            const localVarPath = `/api/live/{id}/submit`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 我的直播列表（志愿者）
         * @param {string} [status]
         * @param {number} [page]
         * @param {number} [pageSize]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLiveMineGet: async (status, page, pageSize, options = {}) => {
            const localVarPath = `/api/live/mine`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }
            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }
            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary 创建直播草稿（志愿者）
         * @param {ApiLiveBody} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLivePost: async (body, options = {}) => {
            const localVarPath = `/api/live`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            localVarHeaderParameter['Content-Type'] = 'application/json';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    };
};
/**
 * LiveApi - functional programming interface
 * @export
 */
export const LiveApiFp = function (configuration) {
    return {
        /**
         *
         * @summary 管理端直播列表（学院/平台管理员）
         * @param {string} [status] 默认 REVIEW
         * @param {number} [collegeId]
         * @param {number} [anchorId]
         * @param {string} [search]
         * @param {number} [page]
         * @param {number} [pageSize]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveAdminGet(status, collegeId, anchorId, search, page, pageSize, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveAdminGet(status, collegeId, anchorId, search, page, pageSize, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 直播列表（公开）
         * @param {string} [tab]
         * @param {number} [collegeId]
         * @param {string} [search]
         * @param {number} [page]
         * @param {number} [pageSize]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveGet(tab, collegeId, search, page, pageSize, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveGet(tab, collegeId, search, page, pageSize, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 获取 Agora RTC Token（登录用户）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdAgoraRtcTokenPost(id, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveIdAgoraRtcTokenPost(id, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 审核直播（学院管理员）
         * @param {string} id
         * @param {IdAuditBody1} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdAuditPost(id, body, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveIdAuditPost(id, body, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 结束直播（志愿者）
         * @param {string} id
         * @param {IdFinishBody} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdFinishPost(id, body, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveIdFinishPost(id, body, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 直播详情（公开）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdGet(id, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveIdGet(id, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 直播消息列表（登录用户）
         * @param {string} id
         * @param {number} [afterId]
         * @param {number} [limit]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdMessagesGet(id, afterId, limit, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveIdMessagesGet(id, afterId, limit, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 发送直播消息（登录用户）
         * @param {string} id
         * @param {IdMessagesBody} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdMessagesPost(id, body, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveIdMessagesPost(id, body, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 下架直播（志愿者/管理员）
         * @param {string} id
         * @param {IdOfflineBody1} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdOfflinePost(id, body, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveIdOfflinePost(id, body, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 上架直播（志愿者）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdPublishPost(id, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveIdPublishPost(id, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 开始直播（志愿者）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdStartPost(id, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveIdStartPost(id, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 获取直播推/拉流信息（登录用户）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdStreamGet(id, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveIdStreamGet(id, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 提交直播审核（志愿者）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdSubmitPost(id, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveIdSubmitPost(id, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 我的直播列表（志愿者）
         * @param {string} [status]
         * @param {number} [page]
         * @param {number} [pageSize]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveMineGet(status, page, pageSize, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLiveMineGet(status, page, pageSize, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary 创建直播草稿（志愿者）
         * @param {ApiLiveBody} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLivePost(body, options) {
            const localVarAxiosArgs = await LiveApiAxiosParamCreator(configuration).apiLivePost(body, options);
            return (axios = globalAxios, basePath = BASE_PATH) => {
                const axiosRequestArgs = { ...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url };
                return axios.request(axiosRequestArgs);
            };
        },
    };
};
/**
 * LiveApi - factory interface
 * @export
 */
export const LiveApiFactory = function (configuration, basePath, axios) {
    return {
        /**
         *
         * @summary 管理端直播列表（学院/平台管理员）
         * @param {string} [status] 默认 REVIEW
         * @param {number} [collegeId]
         * @param {number} [anchorId]
         * @param {string} [search]
         * @param {number} [page]
         * @param {number} [pageSize]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveAdminGet(status, collegeId, anchorId, search, page, pageSize, options) {
            return LiveApiFp(configuration).apiLiveAdminGet(status, collegeId, anchorId, search, page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 直播列表（公开）
         * @param {string} [tab]
         * @param {number} [collegeId]
         * @param {string} [search]
         * @param {number} [page]
         * @param {number} [pageSize]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveGet(tab, collegeId, search, page, pageSize, options) {
            return LiveApiFp(configuration).apiLiveGet(tab, collegeId, search, page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 获取 Agora RTC Token（登录用户）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdAgoraRtcTokenPost(id, options) {
            return LiveApiFp(configuration).apiLiveIdAgoraRtcTokenPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 审核直播（学院管理员）
         * @param {string} id
         * @param {IdAuditBody1} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdAuditPost(id, body, options) {
            return LiveApiFp(configuration).apiLiveIdAuditPost(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 结束直播（志愿者）
         * @param {string} id
         * @param {IdFinishBody} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdFinishPost(id, body, options) {
            return LiveApiFp(configuration).apiLiveIdFinishPost(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 直播详情（公开）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdGet(id, options) {
            return LiveApiFp(configuration).apiLiveIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 直播消息列表（登录用户）
         * @param {string} id
         * @param {number} [afterId]
         * @param {number} [limit]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdMessagesGet(id, afterId, limit, options) {
            return LiveApiFp(configuration).apiLiveIdMessagesGet(id, afterId, limit, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 发送直播消息（登录用户）
         * @param {string} id
         * @param {IdMessagesBody} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdMessagesPost(id, body, options) {
            return LiveApiFp(configuration).apiLiveIdMessagesPost(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 下架直播（志愿者/管理员）
         * @param {string} id
         * @param {IdOfflineBody1} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdOfflinePost(id, body, options) {
            return LiveApiFp(configuration).apiLiveIdOfflinePost(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 上架直播（志愿者）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdPublishPost(id, options) {
            return LiveApiFp(configuration).apiLiveIdPublishPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 开始直播（志愿者）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdStartPost(id, options) {
            return LiveApiFp(configuration).apiLiveIdStartPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 获取直播推/拉流信息（登录用户）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdStreamGet(id, options) {
            return LiveApiFp(configuration).apiLiveIdStreamGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 提交直播审核（志愿者）
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveIdSubmitPost(id, options) {
            return LiveApiFp(configuration).apiLiveIdSubmitPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 我的直播列表（志愿者）
         * @param {string} [status]
         * @param {number} [page]
         * @param {number} [pageSize]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLiveMineGet(status, page, pageSize, options) {
            return LiveApiFp(configuration).apiLiveMineGet(status, page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary 创建直播草稿（志愿者）
         * @param {ApiLiveBody} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLivePost(body, options) {
            return LiveApiFp(configuration).apiLivePost(body, options).then((request) => request(axios, basePath));
        },
    };
};
/**
 * LiveApi - object-oriented interface
 * @export
 * @class LiveApi
 * @extends {BaseAPI}
 */
export class LiveApi extends BaseAPI {
    /**
     *
     * @summary 管理端直播列表（学院/平台管理员）
     * @param {string} [status] 默认 REVIEW
     * @param {number} [collegeId]
     * @param {number} [anchorId]
     * @param {string} [search]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveAdminGet(status, collegeId, anchorId, search, page, pageSize, options) {
        return LiveApiFp(this.configuration).apiLiveAdminGet(status, collegeId, anchorId, search, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 直播列表（公开）
     * @param {string} [tab]
     * @param {number} [collegeId]
     * @param {string} [search]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveGet(tab, collegeId, search, page, pageSize, options) {
        return LiveApiFp(this.configuration).apiLiveGet(tab, collegeId, search, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 获取 Agora RTC Token（登录用户）
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveIdAgoraRtcTokenPost(id, options) {
        return LiveApiFp(this.configuration).apiLiveIdAgoraRtcTokenPost(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 审核直播（学院管理员）
     * @param {string} id
     * @param {IdAuditBody1} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveIdAuditPost(id, body, options) {
        return LiveApiFp(this.configuration).apiLiveIdAuditPost(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 结束直播（志愿者）
     * @param {string} id
     * @param {IdFinishBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveIdFinishPost(id, body, options) {
        return LiveApiFp(this.configuration).apiLiveIdFinishPost(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 直播详情（公开）
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveIdGet(id, options) {
        return LiveApiFp(this.configuration).apiLiveIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 直播消息列表（登录用户）
     * @param {string} id
     * @param {number} [afterId]
     * @param {number} [limit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveIdMessagesGet(id, afterId, limit, options) {
        return LiveApiFp(this.configuration).apiLiveIdMessagesGet(id, afterId, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 发送直播消息（登录用户）
     * @param {string} id
     * @param {IdMessagesBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveIdMessagesPost(id, body, options) {
        return LiveApiFp(this.configuration).apiLiveIdMessagesPost(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 下架直播（志愿者/管理员）
     * @param {string} id
     * @param {IdOfflineBody1} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveIdOfflinePost(id, body, options) {
        return LiveApiFp(this.configuration).apiLiveIdOfflinePost(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 上架直播（志愿者）
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveIdPublishPost(id, options) {
        return LiveApiFp(this.configuration).apiLiveIdPublishPost(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 开始直播（志愿者）
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveIdStartPost(id, options) {
        return LiveApiFp(this.configuration).apiLiveIdStartPost(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 获取直播推/拉流信息（登录用户）
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveIdStreamGet(id, options) {
        return LiveApiFp(this.configuration).apiLiveIdStreamGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 提交直播审核（志愿者）
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveIdSubmitPost(id, options) {
        return LiveApiFp(this.configuration).apiLiveIdSubmitPost(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 我的直播列表（志愿者）
     * @param {string} [status]
     * @param {number} [page]
     * @param {number} [pageSize]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLiveMineGet(status, page, pageSize, options) {
        return LiveApiFp(this.configuration).apiLiveMineGet(status, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary 创建直播草稿（志愿者）
     * @param {ApiLiveBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LiveApi
     */
    async apiLivePost(body, options) {
        return LiveApiFp(this.configuration).apiLivePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
