/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
import { InlineResponse201 } from '../models';
import { OssUploadurlBody } from '../models';
/**
 * OSSApi - axios parameter creator
 * @export
 */
export declare const OSSApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary 后端代传上传文件到 OSS（multipart）
     * @param {string} folder
     * @param {Blob} [file]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiOssUploadFolderPostForm: (folder: string, file?: Blob, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary 获取直传上传 URL（S3 预签名 PUT）
     * @param {OssUploadurlBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiOssUploadUrlPost: (body?: OssUploadurlBody, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary 获取私有对象临时访问 URL（S3 预签名 GET）
     * @param {string} keyOrUrl 对象 key（如 videos/2026/01/19/xxx.mp4）或完整 http(s) URL
     * @param {number} [expiresInSeconds]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiOssUrlGet: (keyOrUrl: string, expiresInSeconds?: number, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * OSSApi - functional programming interface
 * @export
 */
export declare const OSSApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary 后端代传上传文件到 OSS（multipart）
     * @param {string} folder
     * @param {Blob} [file]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiOssUploadFolderPostForm(folder: string, file?: Blob, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse201>>>;
    /**
     *
     * @summary 获取直传上传 URL（S3 预签名 PUT）
     * @param {OssUploadurlBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiOssUploadUrlPost(body?: OssUploadurlBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse201>>>;
    /**
     *
     * @summary 获取私有对象临时访问 URL（S3 预签名 GET）
     * @param {string} keyOrUrl 对象 key（如 videos/2026/01/19/xxx.mp4）或完整 http(s) URL
     * @param {number} [expiresInSeconds]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiOssUrlGet(keyOrUrl: string, expiresInSeconds?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse201>>>;
};
/**
 * OSSApi - factory interface
 * @export
 */
export declare const OSSApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary 后端代传上传文件到 OSS（multipart）
     * @param {string} folder
     * @param {Blob} [file]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiOssUploadFolderPostForm(folder: string, file?: Blob, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>>;
    /**
     *
     * @summary 获取直传上传 URL（S3 预签名 PUT）
     * @param {OssUploadurlBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiOssUploadUrlPost(body?: OssUploadurlBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>>;
    /**
     *
     * @summary 获取私有对象临时访问 URL（S3 预签名 GET）
     * @param {string} keyOrUrl 对象 key（如 videos/2026/01/19/xxx.mp4）或完整 http(s) URL
     * @param {number} [expiresInSeconds]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiOssUrlGet(keyOrUrl: string, expiresInSeconds?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>>;
};
/**
 * OSSApi - object-oriented interface
 * @export
 * @class OSSApi
 * @extends {BaseAPI}
 */
export declare class OSSApi extends BaseAPI {
    /**
     *
     * @summary 后端代传上传文件到 OSS（multipart）
     * @param {string} folder
     * @param {Blob} [file]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OSSApi
     */
    apiOssUploadFolderPostForm(folder: string, file?: Blob, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>>;
    /**
     *
     * @summary 获取直传上传 URL（S3 预签名 PUT）
     * @param {OssUploadurlBody} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OSSApi
     */
    apiOssUploadUrlPost(body?: OssUploadurlBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>>;
    /**
     *
     * @summary 获取私有对象临时访问 URL（S3 预签名 GET）
     * @param {string} keyOrUrl 对象 key（如 videos/2026/01/19/xxx.mp4）或完整 http(s) URL
     * @param {number} [expiresInSeconds]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OSSApi
     */
    apiOssUrlGet(keyOrUrl: string, expiresInSeconds?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>>;
}
