/* tslint:disable */
/* eslint-disable */
/**
 * ETGY Backend API
 * API documentation generated from Zod schemas (auto sync with validation).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ApiVideosBody } from '../models';
import { AuditBatchBody } from '../models';
import { BaseResponse } from '../models';
import { CommentIdAuditBody } from '../models';
import { ErrorResponse } from '../models';
import { IdAuditBody } from '../models';
import { IdCommentsBody } from '../models';
import { IdOfflineBody } from '../models';
import { IdWatchBody } from '../models';
import { InlineResponse2002 } from '../models';
import { InlineResponse2003 } from '../models';
import { InlineResponse2004 } from '../models';
import { InlineResponse2005 } from '../models';
import { InlineResponse201 } from '../models';
import { InlineResponse2012 } from '../models';
import { InlineResponse2013 } from '../models';
import { VideosIdBody } from '../models';
/**
 * VideosApi - axios parameter creator
 * @export
 */
export const VideosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 管理端使用：默认返回待审核(REVIEW)视频，可按 status/collegeId/uploaderId/search 等筛选。平台管理员可跨学院查看；学院管理员仅能查看本学院。
         * @summary 管理端视频列表（学院/平台管理员）
         * @param {string} [status] 
         * @param {number} [collegeId] 
         * @param {number} [uploaderId] 
         * @param {string} [search] 
         * @param {string} [grade] 
         * @param {string} [subject] 
         * @param {string} [sort] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosAdminGet: async (status?: string, collegeId?: number, uploaderId?: number, search?: string, grade?: string, subject?: string, sort?: string, page?: number, pageSize?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/videos/admin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (collegeId !== undefined) {
                localVarQueryParameter['collegeId'] = collegeId;
            }

            if (uploaderId !== undefined) {
                localVarQueryParameter['uploaderId'] = uploaderId;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (grade !== undefined) {
                localVarQueryParameter['grade'] = grade;
            }

            if (subject !== undefined) {
                localVarQueryParameter['subject'] = subject;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 批量审核视频（学院管理员）
         * @param {AuditBatchBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosAuditBatchPost: async (body?: AuditBatchBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/videos/audit/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 审核评论（管理员）
         * @param {string} commentId 
         * @param {CommentIdAuditBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosCommentsCommentIdAuditPost: async (commentId: string, body?: CommentIdAuditBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            if (commentId === null || commentId === undefined) {
                throw new RequiredError('commentId','Required parameter commentId was null or undefined when calling apiVideosCommentsCommentIdAuditPost.');
            }
            const localVarPath = `/api/videos/comments/{commentId}/audit`
                .replace(`{${"commentId"}}`, encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 游客/儿童仅可获取已发布(PUBLISHED)内容；search 或请求非 PUBLISHED 时需登录。
         * @summary 获取视频列表（公开）
         * @param {string} [status] 
         * @param {number} [collegeId] 
         * @param {number} [uploaderId] 
         * @param {string} [search] 
         * @param {string} [grade] 
         * @param {string} [subject] 
         * @param {string} [sort] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosGet: async (status?: string, collegeId?: number, uploaderId?: number, search?: string, grade?: string, subject?: string, sort?: string, page?: number, pageSize?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/videos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (collegeId !== undefined) {
                localVarQueryParameter['collegeId'] = collegeId;
            }

            if (uploaderId !== undefined) {
                localVarQueryParameter['uploaderId'] = uploaderId;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (grade !== undefined) {
                localVarQueryParameter['grade'] = grade;
            }

            if (subject !== undefined) {
                localVarQueryParameter['subject'] = subject;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 审核视频（学院管理员）
         * @param {string} id 
         * @param {IdAuditBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdAuditPost: async (id: string, body?: IdAuditBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdAuditPost.');
            }
            const localVarPath = `/api/videos/{id}/audit`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取视频评论列表（公开：仅已通过）
         * @param {string} id 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdCommentsGet: async (id: string, page?: number, pageSize?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdCommentsGet.');
            }
            const localVarPath = `/api/videos/{id}/comments`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 发表评论（儿童/登录用户，默认待审核）
         * @param {string} id 
         * @param {IdCommentsBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdCommentsPost: async (id: string, body?: IdCommentsBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdCommentsPost.');
            }
            const localVarPath = `/api/videos/{id}/comments`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除视频（志愿者：草稿/驳回）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdDelete: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdDelete.');
            }
            const localVarPath = `/api/videos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 收藏/取消收藏（登录用户）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdFavoritePost: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdFavoritePost.');
            }
            const localVarPath = `/api/videos/{id}/favorite`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取视频详情（公开）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdGet.');
            }
            const localVarPath = `/api/videos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 点赞/取消点赞（登录用户）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdLikePost: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdLikePost.');
            }
            const localVarPath = `/api/videos/{id}/like`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 返回视频与封面图的 presigned GET URL。游客仅能获取已发布(PUBLISHED)视频。
         * @summary 获取视频/封面临时访问 URL（私有桶预签名）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdMediaUrlsGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdMediaUrlsGet.');
            }
            const localVarPath = `/api/videos/{id}/media-urls`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 下架视频（志愿者/管理员）
         * @param {string} id 
         * @param {IdOfflineBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdOfflinePost: async (id: string, body?: IdOfflineBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdOfflinePost.');
            }
            const localVarPath = `/api/videos/{id}/offline`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 编辑视频（志愿者：草稿/驳回）
         * @param {string} id 
         * @param {VideosIdBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdPatch: async (id: string, body?: VideosIdBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdPatch.');
            }
            const localVarPath = `/api/videos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 发布视频（志愿者）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdPublishPost: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdPublishPost.');
            }
            const localVarPath = `/api/videos/{id}/publish`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 提交视频审核（志愿者）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdSubmitPost: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdSubmitPost.');
            }
            const localVarPath = `/api/videos/{id}/submit`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 上报学习/播放记录（登录用户）
         * @param {string} id 
         * @param {IdWatchBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosIdWatchPost: async (id: string, body?: IdWatchBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiVideosIdWatchPost.');
            }
            const localVarPath = `/api/videos/{id}/watch`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 志愿者视频数据面板（我的）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosMineDashboardGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/videos/mine/dashboard`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 创建视频草稿（志愿者）
         * @param {ApiVideosBody} [body] Create video draft
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosPost: async (body?: ApiVideosBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/videos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取我的学习/播放记录（登录用户）
         * @param {number} [videoId] 
         * @param {boolean} [completed] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVideosWatchLogsGet: async (videoId?: number, completed?: boolean, page?: number, pageSize?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/videos/watch-logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (videoId !== undefined) {
                localVarQueryParameter['videoId'] = videoId;
            }

            if (completed !== undefined) {
                localVarQueryParameter['completed'] = completed;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VideosApi - functional programming interface
 * @export
 */
export const VideosApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 管理端使用：默认返回待审核(REVIEW)视频，可按 status/collegeId/uploaderId/search 等筛选。平台管理员可跨学院查看；学院管理员仅能查看本学院。
         * @summary 管理端视频列表（学院/平台管理员）
         * @param {string} [status] 
         * @param {number} [collegeId] 
         * @param {number} [uploaderId] 
         * @param {string} [search] 
         * @param {string} [grade] 
         * @param {string} [subject] 
         * @param {string} [sort] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosAdminGet(status?: string, collegeId?: number, uploaderId?: number, search?: string, grade?: string, subject?: string, sort?: string, page?: number, pageSize?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse201>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosAdminGet(status, collegeId, uploaderId, search, grade, subject, sort, page, pageSize, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 批量审核视频（学院管理员）
         * @param {AuditBatchBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosAuditBatchPost(body?: AuditBatchBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse201>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosAuditBatchPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 审核评论（管理员）
         * @param {string} commentId 
         * @param {CommentIdAuditBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosCommentsCommentIdAuditPost(commentId: string, body?: CommentIdAuditBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2013>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosCommentsCommentIdAuditPost(commentId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 游客/儿童仅可获取已发布(PUBLISHED)内容；search 或请求非 PUBLISHED 时需登录。
         * @summary 获取视频列表（公开）
         * @param {string} [status] 
         * @param {number} [collegeId] 
         * @param {number} [uploaderId] 
         * @param {string} [search] 
         * @param {string} [grade] 
         * @param {string} [subject] 
         * @param {string} [sort] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosGet(status?: string, collegeId?: number, uploaderId?: number, search?: string, grade?: string, subject?: string, sort?: string, page?: number, pageSize?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2002>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosGet(status, collegeId, uploaderId, search, grade, subject, sort, page, pageSize, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 审核视频（学院管理员）
         * @param {string} id 
         * @param {IdAuditBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdAuditPost(id: string, body?: IdAuditBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2012>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdAuditPost(id, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取视频评论列表（公开：仅已通过）
         * @param {string} id 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdCommentsGet(id: string, page?: number, pageSize?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2003>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdCommentsGet(id, page, pageSize, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 发表评论（儿童/登录用户，默认待审核）
         * @param {string} id 
         * @param {IdCommentsBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdCommentsPost(id: string, body?: IdCommentsBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2013>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdCommentsPost(id, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 删除视频（志愿者：草稿/驳回）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdDelete(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse201>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdDelete(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 收藏/取消收藏（登录用户）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdFavoritePost(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse201>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdFavoritePost(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取视频详情（公开）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2012>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 点赞/取消点赞（登录用户）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdLikePost(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse201>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdLikePost(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 返回视频与封面图的 presigned GET URL。游客仅能获取已发布(PUBLISHED)视频。
         * @summary 获取视频/封面临时访问 URL（私有桶预签名）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdMediaUrlsGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse201>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdMediaUrlsGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 下架视频（志愿者/管理员）
         * @param {string} id 
         * @param {IdOfflineBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdOfflinePost(id: string, body?: IdOfflineBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2012>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdOfflinePost(id, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 编辑视频（志愿者：草稿/驳回）
         * @param {string} id 
         * @param {VideosIdBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdPatch(id: string, body?: VideosIdBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2012>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdPatch(id, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 发布视频（志愿者）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdPublishPost(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2012>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdPublishPost(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 提交视频审核（志愿者）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdSubmitPost(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<BaseResponse>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdSubmitPost(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 上报学习/播放记录（登录用户）
         * @param {string} id 
         * @param {IdWatchBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdWatchPost(id: string, body?: IdWatchBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2004>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosIdWatchPost(id, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 志愿者视频数据面板（我的）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosMineDashboardGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse201>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosMineDashboardGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 创建视频草稿（志愿者）
         * @param {ApiVideosBody} [body] Create video draft
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosPost(body?: ApiVideosBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2012>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 获取我的学习/播放记录（登录用户）
         * @param {number} [videoId] 
         * @param {boolean} [completed] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosWatchLogsGet(videoId?: number, completed?: boolean, page?: number, pageSize?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2005>>> {
            const localVarAxiosArgs = await VideosApiAxiosParamCreator(configuration).apiVideosWatchLogsGet(videoId, completed, page, pageSize, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * VideosApi - factory interface
 * @export
 */
export const VideosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 管理端使用：默认返回待审核(REVIEW)视频，可按 status/collegeId/uploaderId/search 等筛选。平台管理员可跨学院查看；学院管理员仅能查看本学院。
         * @summary 管理端视频列表（学院/平台管理员）
         * @param {string} [status] 
         * @param {number} [collegeId] 
         * @param {number} [uploaderId] 
         * @param {string} [search] 
         * @param {string} [grade] 
         * @param {string} [subject] 
         * @param {string} [sort] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosAdminGet(status?: string, collegeId?: number, uploaderId?: number, search?: string, grade?: string, subject?: string, sort?: string, page?: number, pageSize?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>> {
            return VideosApiFp(configuration).apiVideosAdminGet(status, collegeId, uploaderId, search, grade, subject, sort, page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 批量审核视频（学院管理员）
         * @param {AuditBatchBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosAuditBatchPost(body?: AuditBatchBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>> {
            return VideosApiFp(configuration).apiVideosAuditBatchPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 审核评论（管理员）
         * @param {string} commentId 
         * @param {CommentIdAuditBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosCommentsCommentIdAuditPost(commentId: string, body?: CommentIdAuditBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2013>> {
            return VideosApiFp(configuration).apiVideosCommentsCommentIdAuditPost(commentId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 游客/儿童仅可获取已发布(PUBLISHED)内容；search 或请求非 PUBLISHED 时需登录。
         * @summary 获取视频列表（公开）
         * @param {string} [status] 
         * @param {number} [collegeId] 
         * @param {number} [uploaderId] 
         * @param {string} [search] 
         * @param {string} [grade] 
         * @param {string} [subject] 
         * @param {string} [sort] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosGet(status?: string, collegeId?: number, uploaderId?: number, search?: string, grade?: string, subject?: string, sort?: string, page?: number, pageSize?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2002>> {
            return VideosApiFp(configuration).apiVideosGet(status, collegeId, uploaderId, search, grade, subject, sort, page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 审核视频（学院管理员）
         * @param {string} id 
         * @param {IdAuditBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdAuditPost(id: string, body?: IdAuditBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2012>> {
            return VideosApiFp(configuration).apiVideosIdAuditPost(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取视频评论列表（公开：仅已通过）
         * @param {string} id 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdCommentsGet(id: string, page?: number, pageSize?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2003>> {
            return VideosApiFp(configuration).apiVideosIdCommentsGet(id, page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 发表评论（儿童/登录用户，默认待审核）
         * @param {string} id 
         * @param {IdCommentsBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdCommentsPost(id: string, body?: IdCommentsBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2013>> {
            return VideosApiFp(configuration).apiVideosIdCommentsPost(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除视频（志愿者：草稿/驳回）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdDelete(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>> {
            return VideosApiFp(configuration).apiVideosIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 收藏/取消收藏（登录用户）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdFavoritePost(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>> {
            return VideosApiFp(configuration).apiVideosIdFavoritePost(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取视频详情（公开）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdGet(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2012>> {
            return VideosApiFp(configuration).apiVideosIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 点赞/取消点赞（登录用户）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdLikePost(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>> {
            return VideosApiFp(configuration).apiVideosIdLikePost(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 返回视频与封面图的 presigned GET URL。游客仅能获取已发布(PUBLISHED)视频。
         * @summary 获取视频/封面临时访问 URL（私有桶预签名）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdMediaUrlsGet(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>> {
            return VideosApiFp(configuration).apiVideosIdMediaUrlsGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 下架视频（志愿者/管理员）
         * @param {string} id 
         * @param {IdOfflineBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdOfflinePost(id: string, body?: IdOfflineBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2012>> {
            return VideosApiFp(configuration).apiVideosIdOfflinePost(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 编辑视频（志愿者：草稿/驳回）
         * @param {string} id 
         * @param {VideosIdBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdPatch(id: string, body?: VideosIdBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2012>> {
            return VideosApiFp(configuration).apiVideosIdPatch(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 发布视频（志愿者）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdPublishPost(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2012>> {
            return VideosApiFp(configuration).apiVideosIdPublishPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 提交视频审核（志愿者）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdSubmitPost(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<BaseResponse>> {
            return VideosApiFp(configuration).apiVideosIdSubmitPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 上报学习/播放记录（登录用户）
         * @param {string} id 
         * @param {IdWatchBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosIdWatchPost(id: string, body?: IdWatchBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2004>> {
            return VideosApiFp(configuration).apiVideosIdWatchPost(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 志愿者视频数据面板（我的）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosMineDashboardGet(options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse201>> {
            return VideosApiFp(configuration).apiVideosMineDashboardGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 创建视频草稿（志愿者）
         * @param {ApiVideosBody} [body] Create video draft
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosPost(body?: ApiVideosBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2012>> {
            return VideosApiFp(configuration).apiVideosPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取我的学习/播放记录（登录用户）
         * @param {number} [videoId] 
         * @param {boolean} [completed] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVideosWatchLogsGet(videoId?: number, completed?: boolean, page?: number, pageSize?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2005>> {
            return VideosApiFp(configuration).apiVideosWatchLogsGet(videoId, completed, page, pageSize, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VideosApi - object-oriented interface
 * @export
 * @class VideosApi
 * @extends {BaseAPI}
 */
export class VideosApi extends BaseAPI {
    /**
     * 管理端使用：默认返回待审核(REVIEW)视频，可按 status/collegeId/uploaderId/search 等筛选。平台管理员可跨学院查看；学院管理员仅能查看本学院。
     * @summary 管理端视频列表（学院/平台管理员）
     * @param {string} [status] 
     * @param {number} [collegeId] 
     * @param {number} [uploaderId] 
     * @param {string} [search] 
     * @param {string} [grade] 
     * @param {string} [subject] 
     * @param {string} [sort] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosAdminGet(status?: string, collegeId?: number, uploaderId?: number, search?: string, grade?: string, subject?: string, sort?: string, page?: number, pageSize?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse201>> {
        return VideosApiFp(this.configuration).apiVideosAdminGet(status, collegeId, uploaderId, search, grade, subject, sort, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 批量审核视频（学院管理员）
     * @param {AuditBatchBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosAuditBatchPost(body?: AuditBatchBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse201>> {
        return VideosApiFp(this.configuration).apiVideosAuditBatchPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 审核评论（管理员）
     * @param {string} commentId 
     * @param {CommentIdAuditBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosCommentsCommentIdAuditPost(commentId: string, body?: CommentIdAuditBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2013>> {
        return VideosApiFp(this.configuration).apiVideosCommentsCommentIdAuditPost(commentId, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 游客/儿童仅可获取已发布(PUBLISHED)内容；search 或请求非 PUBLISHED 时需登录。
     * @summary 获取视频列表（公开）
     * @param {string} [status] 
     * @param {number} [collegeId] 
     * @param {number} [uploaderId] 
     * @param {string} [search] 
     * @param {string} [grade] 
     * @param {string} [subject] 
     * @param {string} [sort] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosGet(status?: string, collegeId?: number, uploaderId?: number, search?: string, grade?: string, subject?: string, sort?: string, page?: number, pageSize?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2002>> {
        return VideosApiFp(this.configuration).apiVideosGet(status, collegeId, uploaderId, search, grade, subject, sort, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 审核视频（学院管理员）
     * @param {string} id 
     * @param {IdAuditBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdAuditPost(id: string, body?: IdAuditBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2012>> {
        return VideosApiFp(this.configuration).apiVideosIdAuditPost(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取视频评论列表（公开：仅已通过）
     * @param {string} id 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdCommentsGet(id: string, page?: number, pageSize?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2003>> {
        return VideosApiFp(this.configuration).apiVideosIdCommentsGet(id, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 发表评论（儿童/登录用户，默认待审核）
     * @param {string} id 
     * @param {IdCommentsBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdCommentsPost(id: string, body?: IdCommentsBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2013>> {
        return VideosApiFp(this.configuration).apiVideosIdCommentsPost(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 删除视频（志愿者：草稿/驳回）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdDelete(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse201>> {
        return VideosApiFp(this.configuration).apiVideosIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 收藏/取消收藏（登录用户）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdFavoritePost(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse201>> {
        return VideosApiFp(this.configuration).apiVideosIdFavoritePost(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取视频详情（公开）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdGet(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2012>> {
        return VideosApiFp(this.configuration).apiVideosIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 点赞/取消点赞（登录用户）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdLikePost(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse201>> {
        return VideosApiFp(this.configuration).apiVideosIdLikePost(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 返回视频与封面图的 presigned GET URL。游客仅能获取已发布(PUBLISHED)视频。
     * @summary 获取视频/封面临时访问 URL（私有桶预签名）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdMediaUrlsGet(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse201>> {
        return VideosApiFp(this.configuration).apiVideosIdMediaUrlsGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 下架视频（志愿者/管理员）
     * @param {string} id 
     * @param {IdOfflineBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdOfflinePost(id: string, body?: IdOfflineBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2012>> {
        return VideosApiFp(this.configuration).apiVideosIdOfflinePost(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 编辑视频（志愿者：草稿/驳回）
     * @param {string} id 
     * @param {VideosIdBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdPatch(id: string, body?: VideosIdBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2012>> {
        return VideosApiFp(this.configuration).apiVideosIdPatch(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 发布视频（志愿者）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdPublishPost(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2012>> {
        return VideosApiFp(this.configuration).apiVideosIdPublishPost(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 提交视频审核（志愿者）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdSubmitPost(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<BaseResponse>> {
        return VideosApiFp(this.configuration).apiVideosIdSubmitPost(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 上报学习/播放记录（登录用户）
     * @param {string} id 
     * @param {IdWatchBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosIdWatchPost(id: string, body?: IdWatchBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2004>> {
        return VideosApiFp(this.configuration).apiVideosIdWatchPost(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 志愿者视频数据面板（我的）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosMineDashboardGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse201>> {
        return VideosApiFp(this.configuration).apiVideosMineDashboardGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 创建视频草稿（志愿者）
     * @param {ApiVideosBody} [body] Create video draft
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosPost(body?: ApiVideosBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2012>> {
        return VideosApiFp(this.configuration).apiVideosPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 获取我的学习/播放记录（登录用户）
     * @param {number} [videoId] 
     * @param {boolean} [completed] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApi
     */
    public async apiVideosWatchLogsGet(videoId?: number, completed?: boolean, page?: number, pageSize?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2005>> {
        return VideosApiFp(this.configuration).apiVideosWatchLogsGet(videoId, completed, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
}
